bind_host = "127.0.0.1"
bind_port = 3867

[backends.freenode]
path = "target/debug/irc-backend"

    [backends.freenode.config]
    host = "chat.freenode.net"
    nick = "flubber"
    port = 6697
    ssl = true
